### ISSUE TITLE
yolox

### ISSUE THREAD

**Issue by fyodor-rs** [shouxieai/tensorRT_Pro#113]
请问支持yolox nano模型吗

**Comment by shouxieai** [comment]
支持

**Comment by shouxieai** [comment]
https://github.com/shouxieai/tensorRT_Pro/blob/61c494f2bc1a6a6f237e8e9bba08ab1c19e0ced0/src/application/app_yolo/yolo.hpp#L23

**Comment by fyodor-rs** [comment]
> https://github.com/shouxieai/tensorRT_Pro/blob/61c494f2bc1a6a6f237e8e9bba08ab1c19e0ced0/src/application/app_yolo/yolo.hpp#L23

> https://github.com/shouxieai/tensorRT_Pro/blob/61c494f2bc1a6a6f237e8e9bba08ab1c19e0ced0/src/application/app_yolo/yolo.hpp#L23

**Comment by fyodor-rs** [comment]
能转trt吗，好像只支持标准模型

**Comment by fyodor-rs** [comment]
![20220620123424](https://user-images.githubusercontent.com/56202762/174526000-5a625e4b-82c7-48aa-9055-53bc958195d4.png)

**Comment by shouxieai** [comment]
你的output有毛病，是1x-1x6，你有按照要求修改吗

**Comment by fyodor-rs** [comment]
> 你的output有毛病，是1x-1x6，你有按照要求修改吗
请问要修改哪个？  X默认就是1
