### ISSUE TITLE
可以推理输入为单通道的图像吗？代码改了很久没成功。

### ISSUE THREAD

**Issue by short-life** [shouxieai/tensorRT_Pro#120]

**Comment by short-life** [comment]
我把预处理，和image_to_tensor中的仿射变换那部分代码注释了，就不报错，但是预测结果为空。

**Comment by short-life** [comment]
我把warp_affine_bilinear_and_normalize_plane代码尝试改成单通道，最后整个项目已经不报内存错误了（所以应该是访问越界造成最上面的问题），但从保存的图片来看输出是不正确的，所以这个方法还得好好修改。

**Comment by short-life** [comment]
__global__ void warp_affine_bilinear_and_normalize_plane_kernel(uint8_t* src, int src_line_size, int src_width, int src_height, float* dst, int dst_width, int dst_height, 
		uint8_t const_value_st, float* warp_affine_matrix_2_3, Norm norm, int edge){

		int position = blockDim.x * blockIdx.x + threadIdx.x;
		if (position >= edge) return;

		float m_x1 = warp_affine_matrix_2_3[0];
		float m_y1 = warp_affine_matrix_2_3[1];
		float m_z1 = warp_affine_matrix_2_3[2];
		float m_x2 = warp_affine_matrix_2_3[3];
		float m_y2 = warp_affine_matrix_2_3[4];
		float m_z2 = warp_affine_matrix_2_3[5];

		int dx      = position % dst_width;
		int dy      = position / dst_width;

		float src_x = m_x1 * dx + m_y1 * dy + m_z1;
		float src_y = m_x2 * dx + m_y2 * dy + m_z2;
//		float c0, c1, c2;
        float c;

		if(src_x <= -1 || src_x >= src_width || src_y <= -1 || src_y >= src_height){
			// out of range
//			c0 = const_value_st;
//			c1 = const_value_st;
//			c2 = const_value_st;
            c = const_value_st;
		}else{
			int y_low = floorf(src_y);
			int x_low = floorf(src_x);
			int y_high = y_low + 1;
			int x_high = x_low + 1;

			uint8_t const_value[] = {const_value_st, const_value_st, const_value_st};
			float ly    = src_y - y_low;
			float lx    = src_x - x_low;
			float hy    = 1 - ly;
			float hx    = 1 - lx;
			float w1    = hy * hx, w2 = hy * lx, w3 = ly * hx, w4 = ly * lx;
			uint8_t* v1 = const_value;
			uint8_t* v2 = const_value;
			uint8_t* v3 = const_value;
			uint8_t* v4 = const_value;
			if(y_low >= 0){
				if (x_low >= 0)
					v1 = src + y_low * src_line_size + x_low * 1;

				if (x_high < src_width)
					v2 = src + y_low * src_line_size + x_high * 1;
			}
			
			if(y_high < src_height){
				if (x_low >= 0)
					v3 = src + y_high * src_line_size + x_low * 1;

				if (x_high < src_width)
					v4 = src + y_high * src_line_size + x_high * 1;
			}
			
			// same to opencv
//			c0 = floorf(w1 * v1[0] + w2 * v2[0] + w3 * v3[0] + w4 * v4[0] + 0.5f);
//			c1 = floorf(w1 * v1[1] + w2 * v2[1] + w3 * v3[1] + w4 * v4[1] + 0.5f);
//			c2 = floorf(w1 * v1[2] + w2 * v2[2] + w3 * v3[2] + w4 * v4[2] + 0.5f);
            c = floorf(w1 * v1[0] + w2 * v2[0] + w3 * v3[0] + w4 * v4[0] + 0.5f);
		}

//		if(norm.channel_type == ChannelType::Invert){
//			float t = c2;
//			c2 = c0;  c0 = t;
//		}

		if(norm.type == NormType::MeanStd){
//			c0 = (c0 * norm.alpha - norm.mean[0]) / norm.std[0];
//			c1 = (c1 * norm.alpha - norm.mean[1]) / norm.std[1];
//			c2 = (c2 * norm.alpha - norm.mean[2]) / norm.std[2];
            c = (c * norm.alpha - norm.mean[0]) / norm.std[0];
		}else if(norm.type == NormType::AlphaBeta){
//			c0 = c0 * norm.alpha + norm.beta;
//			c1 = c1 * norm.alpha + norm.beta;
//			c2 = c2 * norm.alpha + norm.beta;
            c = c * norm.alpha + norm.beta;
		}

		int area = dst_width * dst_height;
//		float* pdst_c0 = dst + dy * dst_width + dx;
//		float* pdst_c1 = pdst_c0 + area;
//		float* pdst_c2 = pdst_c1 + area;
//		*pdst_c0 = c0;
//		*pdst_c1 = c1;
//		*pdst_c2 = c2;

        float* pdst_c = dst + dy * dst_width + dx;
        *pdst_c = c;
	}

**Comment by shouxieai** [comment]
666

**Comment by short-life** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by OpenCDR** [comment]
@short-life 请问您除了更改了warp_affine_bilinear_and_normalize_plane_kernel的代码外，还更改了哪些呢？

**Comment by short-life** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
