### ISSUE TITLE
对输入输出的内存申请为啥要加个size_matrix 仿射矩阵的大小，而且对输出affine_matrix_device的内存分配是sizeof(job.additional.d2i)

### ISSUE THREAD

**Issue by cqray1990** [shouxieai/tensorRT_Pro#121]
uint8_t* gpu_workspace        = (uint8_t*)workspace->gpu(size_matrix + size_image);
            float*   affine_matrix_device = (float*)gpu_workspace;
            uint8_t* image_device         = size_matrix + gpu_workspace;

            uint8_t* cpu_workspace        = (uint8_t*)workspace->cpu(size_matrix + size_image);
            float* affine_matrix_host     = (float*)cpu_workspace;
            uint8_t* image_host           = size_matrix + cpu_workspace;
           memcpy(image_host, image.data, size_image);
            memcpy(affine_matrix_host, job.additional.d2i, sizeof(job.additional.d2i));
            checkCudaRuntime(cudaMemcpyAsync(image_device, image_host, size_image, cudaMemcpyHostToDevice, preprocess_stream));
            checkCudaRuntime(cudaMemcpyAsync(affine_matrix_device, affine_matrix_host, sizeof(job.additional.d2i), cudaMemcpyHostToDevice, preprocess_stream));

**Comment by shouxieai** [comment]
因为需要在gpu上做warpaffine，所以需要一个矩阵的存储空间做这个操作

**Comment by cqray1990** [comment]
> 因为需要在gpu上做warpaffine，所以需要一个矩阵的存储空间做这个操作
            uint8_t* gpu_workspace        = (uint8_t*)workspace->gpu(size_matrix + size_image);
            float*   affine_matrix_device = (float*)gpu_workspace;

仿射矩阵的申请的不是只需要size_matrix？为啥还多加了size_image，不是多了？

**Comment by shouxieai** [comment]
存储图像跟矩阵啊，两个一起申请了。为啥要分两次申请
