### ISSUE TITLE
 请问输出的parray输出为啥要加1，不可以放在第0的位置？parray是输出首地址，加1不是偏了一个位置？

### ISSUE THREAD

**Issue by cqray1990** [shouxieai/tensorRT_Pro#123]
float* pout_item = parray + 1 + index * NUM_BOX_ELEMENT;
        *pout_item++ = left;
        *pout_item++ = top;
        *pout_item++ = right;
        *pout_item++ = bottom;
        *pout_item++ = confidence;
        *pout_item++ = label;
        *pout_item++ = 1; // 1 = keep, 0 = ignore

**Comment by shouxieai** [comment]
表示这个数组的元素数量
