### ISSUE TITLE
AffineMatrix求解？

### ISSUE THREAD

**Issue by cqray1990** [shouxieai/tensorRT_Pro#124]
正常图像作缩放是不需要偏移的吧？
  M = [
            scale,    0,     -scale * from.width * 0.5 + to.width * 0.5
            0,     scale,    -scale * from.height * 0.5 + to.height * 0.5
            0,        0,                     1
            ]
 -scale * from.width * 0.5 + to.width * 0.5这个偏移量抵消了，

但是第一次平移矩阵不是
 P = [
            1,        0,      -scale * from.width * 0.5
            0,        -1,      scale * from.height * 0.5
            0,        0,                1
            ]
第二次平移矩阵不应该是：
           T = [
            1,        0,      to.width * 0.5,
            0,       - 1,      to.height * 0.5,
            0,        0,            1
            ]

？??
参考的矩阵：
https://www.cnblogs.com/xuanyuyt/p/7112876.html

**Comment by shouxieai** [comment]
你可以把代码对应的行数发来吗？我不知道你针对哪部分来讲的

**Comment by cqray1990** [comment]
> 你可以把代码对应的行数发来吗？我不知道你针对哪部分来讲的

  void compute(const cv::Size& from, const cv::Size& to)函数里面的

**Comment by shouxieai** [comment]
为什么-scale * from.width * 0.5 + to.width * 0.5这个要抵消？，他们并不会抵消
在这个案例里面，需要平移+缩放，因为要平移到图像中心，

另外同时考虑为了使得中心对齐，还要增加一个小的平移量，具体参考在这里：
https://github.com/shouxieai/tensorRT_Pro/blob/ab7bd221f6f93c135ca0fbf1510d9428a9a3c5ee/src/application/app_yolo/yolo.cpp#L88

**Comment by shouxieai** [comment]
关于平移矩阵，你得好好想想是不是你写的那样

**Comment by cqray1990** [comment]
> 关于平移矩阵，你得好好想想是不是你写的那样

第一个平移矩阵是把图像坐标的原点移到笛卡尔坐标的转换矩阵？
第二个平移矩阵是逆变换？ 笛卡尔坐标到新图的图像坐标？

**Comment by shouxieai** [comment]
嗯，对于坐标系的理解角度不同，但是殊途同归
