### ISSUE TITLE
i want to resize input image(width, height) in YOLOV7.

### ISSUE THREAD

**Issue by hacunamatada** [shouxieai/tensorRT_Pro#128]
YoloV7's trt engine is created input image size(640,640).
i want to resize input image's width and height.(for example,(608,608))
what i have to do?

**Comment by shouxieai** [comment]
1. Ensure that the anchor part is not affected by the resolution adjustment
2. Configure the dynamic shape, specify the width and height as dynamic during compilation, and specify it as 608x608 during inference
