### ISSUE TITLE
分类模型是否支持？？？

### ISSUE THREAD

**Issue by liu-qi-lin** [shouxieai/tensorRT_Pro#139]
佬 这个框架是否支持分类模型？ 如果支持的话， 有参考实现代码吗？

**Comment by shouxieai** [comment]
支持分类，但是确实这里面没有具体案例，因为太简单了
这里有个其他案例：https://github.com/shouxieai/learning-cuda-trt/blob/main/tensorrt-integrate-1.1-full-cnn-classifier/src/main.cpp

**Comment by liu-qi-lin** [comment]
感谢大佬
