### ISSUE TITLE
protbuf链接问题 undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)

### ISSUE THREAD

**Issue by damon-he** [shouxieai/tensorRT_Pro#145]
下载了protbuf 3.11.4后，在本地安装后，编译的时候出现如下报错信息:
[100%] Linking CXX executable ../workspace/pro
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_AttributeProto_onnx_2dml_2eproto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:132: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_FunctionProto_onnx_2dml_2eproto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:163: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_ModelProto_onnx_2dml_2eproto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:179: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_OperatorSetIdProto_onnx_2dml_2eproto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:198: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_SparseTensorProto_onnx_2dml_2eproto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:212: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o:/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:227: more undefined references to `google::protobuf::internal::VerifyVersion(int, int, char const*)' follow
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::AttributeProto_AttributeType_descriptor()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:947: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::TensorProto_DataType_descriptor()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:994: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::TensorProto_DataLocation_descriptor()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1045: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::Version_descriptor()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1066: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::OperatorStatus_descriptor()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1087: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::AttributeProto::AttributeProto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1172: undefined reference to `google::protobuf::RepeatedField<float>::RepeatedField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1172: undefined reference to `google::protobuf::RepeatedField<long>::RepeatedField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1172: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1172: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~RepeatedPtrField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1172: undefined reference to `google::protobuf::RepeatedField<long>::~RepeatedField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1172: undefined reference to `google::protobuf::RepeatedField<float>::~RepeatedField()'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1186: undefined reference to `google::protobuf::RepeatedField<float>::RepeatedField(google::protobuf::RepeatedField<float> const&)'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1186: undefined reference to `google::protobuf::RepeatedField<long>::RepeatedField(google::protobuf::RepeatedField<long> const&)'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1186: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1186: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~RepeatedPtrField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1186: undefined reference to `google::protobuf::RepeatedField<long>::~RepeatedField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1186: undefined reference to `google::protobuf::RepeatedField<float>::~RepeatedField()'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::AttributeProto::~AttributeProto()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1241: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~RepeatedPtrField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1241: undefined reference to `google::protobuf::RepeatedField<long>::~RepeatedField()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1241: undefined reference to `google::protobuf::RepeatedField<float>::~RepeatedField()'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `onnx::AttributeProto::Clear()':
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1272: undefined reference to `google::protobuf::RepeatedField<float>::Clear()'
/home/damon/tensorRT_Pro-main/src/tensorRT/onnx/onnx-ml.pb.cpp:1273: undefined reference to `google::protobuf::RepeatedField<long>::Clear()'

**Comment by damon-he** [comment]
cmake生成的工程默认链接静态库，要注意依赖顺序

**Comment by cyrusbehr** [comment]
I'm going to add to the answer to just make it more clear for others. 

Essentially, in the `link_directories` command, `protobuf` must be infront of `TensorRT`, as TensorRt has it's own protobuf files in that directory.

So this works:
```
link_directories(
${PROTOBUF_DIR}/lib
${TENSORRT_DIR}/lib
)
```

This will not work:
```
link_directories(
${TENSORRT_DIR}/lib
${PROTOBUF_DIR}/lib
)
```
