### ISSUE TITLE
NVInfer: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.

### ISSUE THREAD

**Issue by 843124** [shouxieai/tensorRT_Pro#209]
![2](https://github.com/shouxieai/tensorRT_Pro/assets/153380921/a2594393-136a-4e46-af2b-b052a1a2d069)
大佬你好，帮忙看看什么问题

**Comment by 843124** [comment]
> ![2](https://private-user-images.githubusercontent.com/153380921/290161882-a2594393-136a-4e46-af2b-b052a1a2d069.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjUxNjMsIm5iZiI6MTcwMjQ2NDg2MywicGF0aCI6Ii8xNTMzODA5MjEvMjkwMTYxODgyLWEyNTk0MzkzLTEzNmEtNGU0Ni1hZjJiLWIwNTJhMWEyZDA2OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMDU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDgwNjBiZWIxNDFjZTBmYmFiZTYwOTM5ZDliYTUxMDFmOTZmZmQ1YWYwYTM1NmY4ZDNlOTk1YzRmYjZhNGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R62J7vrvG1mxa5A1SV9PJyI5HV5N44om2GJfzc3oMeA) 大佬你好，帮忙看看什么问题

**Comment by scteam1994** [comment]
getMaxBatchSize()在tensorrt8.4以后版本废弃了，不过正常情况会返回1。你这个问题不是这个警告造成的，你可能是模型转换过程出的错，也可能是getMaxBatchSize()异常返回了0.先查一下onnx模型输入维度对不对吧。

**Comment by kuyufei** [comment]
@843124 你好，请问你解决这个问题了吗，我也遇到这个问题了
