### ISSUE TITLE
ModuleNotFoundError:No module named 'trtpy.libtrtpyc'

### ISSUE THREAD

**Issue by sunnyjay3** [shouxieai/tensorRT_Pro#25]
请问这样报错是缺了什么东西么，谢谢
/tensorRT_Pro/python/trtpy/__init__.py",line 303,in<module>
   from .libtrtpyc import *
ModuleNotFoundError:No module named 'trtpy.libtrtpyc'

**Comment by huawang400** [comment]
i have this problemes
