### ISSUE TITLE
undefined reference to symbol 'dlsym@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by Chenhait** [shouxieai/tensorRT_Pro#29]
![2021-10-26 22-11-35屏幕截图](https://user-images.githubusercontent.com/68895932/138896745-0857f7af-762e-4c57-83ba-7a46e4bb6ba7.png)

**Comment by nisi44** [comment]
朋友，我也遇到了这个问题，然后在最开始CMakeLists.txt里的最后一行的库里加了c，就顺利编译成功了，希望你也可以
