### ISSUE TITLE
有人make的时候link出错吗

### ISSUE THREAD

**Issue by ChenXinShuo1998** [shouxieai/tensorRT_Pro#33]

**Comment by shouxieai** [comment]
没有具体错误信息吗？

**Comment by ChenXinShuo1998** [comment]
已经解决了，是probuf的问题，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shouxieai/tensorRT_Pro] 有人make的时候link出错吗 (Issue #33)




 
没有具体错误信息吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
