### ISSUE TITLE
能帮忙看一个编译问题吗？

### ISSUE THREAD

**Issue by PGogo** [shouxieai/tensorRT_Pro#34]
是protobuf的链接有问题吗？该怎么处理呢？谢谢！

root@44ee5adbd43e:/home/pangguoliang/projects/tensorRT_Pro/build# make yolo -j8
[  1%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_dbface/plugin_list_generated_dbface_decode.cu.o
[  2%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_yolo_fast/plugin_list_generated_yolox_decode.cu.o
[  4%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_centernet/plugin_list_generated_centernet_decode.cu.o
[  7%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_retinaface/plugin_list_generated_retinaface_decode.cu.o
[  7%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_scrfd/plugin_list_generated_scrfd_decode.cu.o
[  8%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_yolo/plugin_list_generated_yolo_decode.cu.o
[ 10%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/tensorRT/onnxplugin/plugins/plugin_list_generated_HSwish.cu.o
[ 11%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/application/app_yolo_fast/plugin_list_generated_yolov5_decode.cu.o
[ 13%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/tensorRT/common/plugin_list_generated_preprocess_kernel.cu.o
[ 14%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/tensorRT/onnxplugin/plugins/plugin_list_generated_DCNv2.cu.o
[ 16%] Building NVCC (Device) object CMakeFiles/plugin_list.dir/src/tensorRT/onnxplugin/plugins/plugin_list_generated_HSigmoid.cu.o
Scanning dependencies of target plugin_list
[ 17%] Linking CXX shared library libplugin_list.so
[ 17%] Built target plugin_list
Scanning dependencies of target pro
[ 19%] Building CXX object CMakeFiles/pro.dir/src/application/app_alphapose.cpp.o
[ 20%] Building CXX object CMakeFiles/pro.dir/src/application/app_centernet.cpp.o
[ 22%] Building CXX object CMakeFiles/pro.dir/src/application/app_arcface.cpp.o
[ 23%] Building CXX object CMakeFiles/pro.dir/src/application/app_bert.cpp.o
[ 25%] Building CXX object CMakeFiles/pro.dir/src/application/app_arcface/arcface.cpp.o
[ 26%] Building CXX object CMakeFiles/pro.dir/src/application/app_centernet/centernet.cpp.o
[ 28%] Building CXX object CMakeFiles/pro.dir/src/application/app_dbface.cpp.o
[ 29%] Building CXX object CMakeFiles/pro.dir/src/application/app_alphapose/alpha_pose.cpp.o
[ 31%] Building CXX object CMakeFiles/pro.dir/src/application/app_dbface/dbface.cpp.o
[ 32%] Building CXX object CMakeFiles/pro.dir/src/application/app_fall_gcn/fall_gcn.cpp.o
[ 34%] Building CXX object CMakeFiles/pro.dir/src/application/app_fall_recognize.cpp.o
[ 35%] Building CXX object CMakeFiles/pro.dir/src/application/app_high_performance.cpp.o
[ 37%] Building CXX object CMakeFiles/pro.dir/src/application/app_high_performance/alpha_pose_high_perf.cpp.o
[ 38%] Building CXX object CMakeFiles/pro.dir/src/application/app_high_performance/high_performance.cpp.o
[ 40%] Building CXX object CMakeFiles/pro.dir/src/application/app_high_performance/yolo_high_perf.cpp.o
[ 41%] Building CXX object CMakeFiles/pro.dir/src/application/app_lesson.cpp.o
[ 43%] Building CXX object CMakeFiles/pro.dir/src/application/app_plugin.cpp.o
[ 44%] Building CXX object CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o
[ 46%] Building CXX object CMakeFiles/pro.dir/src/application/app_retinaface.cpp.o
[ 47%] Building CXX object CMakeFiles/pro.dir/src/application/app_retinaface/retinaface.cpp.o
[ 49%] Building CXX object CMakeFiles/pro.dir/src/application/app_scrfd.cpp.o
[ 50%] Building CXX object CMakeFiles/pro.dir/src/application/app_scrfd/scrfd.cpp.o
[ 52%] Building CXX object CMakeFiles/pro.dir/src/application/app_yolo.cpp.o
[ 53%] Building CXX object CMakeFiles/pro.dir/src/application/app_yolo/yolo.cpp.o
[ 55%] Building CXX object CMakeFiles/pro.dir/src/application/app_yolo_fast.cpp.o
[ 56%] Building CXX object CMakeFiles/pro.dir/src/application/app_yolo_fast/yolo_fast.cpp.o
[ 58%] Building CXX object CMakeFiles/pro.dir/src/application/test_warpaffine.cpp.o
[ 59%] Building CXX object CMakeFiles/pro.dir/src/application/test_yolo_map.cpp.o
[ 61%] Building CXX object CMakeFiles/pro.dir/src/application/tools/auto_download.cpp.o
[ 62%] Building CXX object CMakeFiles/pro.dir/src/application/tools/deepsort.cpp.o
[ 64%] Building CXX object CMakeFiles/pro.dir/src/application/tools/zmq_remote_show.cpp.o
[ 65%] Building CXX object CMakeFiles/pro.dir/src/application/tools/zmq_u.cpp.o
[ 67%] Building CXX object CMakeFiles/pro.dir/src/main.cpp.o
[ 68%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/builder/trt_builder.cpp.o
[ 70%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/common/cuda_tools.cpp.o
[ 71%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/common/ilogger.cpp.o
[ 73%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/common/json.cpp.o
[ 74%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/common/trt_tensor.cpp.o
[ 76%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/import_lib.cpp.o
[ 77%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/infer/trt_infer.cpp.o
[ 79%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o
[ 80%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-operators-ml.pb.cpp.o
[ 82%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/LoopHelpers.cpp.o
[ 83%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/ModelImporter.cpp.o
[ 85%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/NvOnnxParser.cpp.o
[ 86%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/OnnxAttrs.cpp.o
[ 88%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/RNNHelpers.cpp.o
[ 89%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/ShapeTensor.cpp.o
[ 91%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/ShapedWeights.cpp.o
[ 92%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/builtin_op_importers.cpp.o
[ 94%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/onnx2trt_utils.cpp.o
[ 95%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnx_parser/onnxErrorRecorder.cpp.o
[ 97%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnxplugin/onnxplugin.cpp.o
[ 98%] Building CXX object CMakeFiles/pro.dir/src/tensorRT/onnxplugin/plugin_binary_io.cpp.o
[100%] Linking CXX executable ../workspace/pro
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_AttributeProto_onnx_2dml_2eproto()':
/home/pangguoliang/projects/tensorRT_Pro/src/tensorRT/onnx/onnx-ml.pb.cpp:132: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
CMakeFiles/pro.dir/src/tensorRT/onnx/onnx-ml.pb.cpp.o: In function `InitDefaultsscc_info_FunctionProto_onnx_2dml_2eproto()':

...

/home/pangguoliang/projects/tensorRT_Pro/src/tensorRT/onnx_parser/onnx2trt_utils.cpp:805: undefined reference to 
CMakeFiles/pro.dir/src/tensorRT/onnx_parser/onnx2trt_utils.cpp.o: In function `onnx2trt::poolingHelper(onnx2trt::IImporterContext*, onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&, nvinfer1::PoolingType)':
/home/pangguoliang/projects/tensorRT_Pro/src/tensorRT/onnx_parser/onnx2trt_utils.cpp:1644: undefined reference to `google::protobuf::RepeatedField<long>::size() const'
CMakeFiles/pro.dir/src/tensorRT/onnx_parser/onnx2trt_utils.cpp.o: In function `onnx2trt::setAttr(nvinfer1::Dims32*, onnx::AttributeProto const*, int, int)':
/home/pangguoliang/projects/tensorRT_Pro/src/tensorRT/onnx_parser/onnx2trt_utils.cpp:1827: undefined reference to `google::protobuf::RepeatedField<long>::size() const'
collect2: error: ld returned 1 exit status
CMakeFiles/pro.dir/build.make:1515: recipe for target '../workspace/pro' failed
make[3]: *** [../workspace/pro] Error 1
CMakeFiles/Makefile2:424: recipe for target 'CMakeFiles/pro.dir/all' failed
make[2]: *** [CMakeFiles/pro.dir/all] Error 2
CMakeFiles/Makefile2:234: recipe for target 'CMakeFiles/yolo.dir/rule' failed
make[1]: *** [CMakeFiles/yolo.dir/rule] Error 2
Makefile:183: recipe for target 'yolo' failed
make: *** [yolo] Error 2

**Comment by shouxieai** [comment]
你是protobuf库没有配置好

**Comment by shouxieai** [comment]
请注意对应版本，3.11.4.

**Comment by shouxieai** [comment]
若你不是3.11.4，请参照readme上写的，不同protobuf版本适配应该怎么做

**Comment by cyrusbehr** [comment]
I'm going to add to the answer to just make it more clear for others. 

Essentially, in the `link_directories` command, `protobuf` must be infront of `TensorRT`, as TensorRt has it's own protobuf files in that directory.

So this works:
```
link_directories(
${PROTOBUF_DIR}/lib
${TENSORRT_DIR}/lib
)
```

This will not work:
```
link_directories(
${TENSORRT_DIR}/lib
${PROTOBUF_DIR}/lib
)
```
