### ISSUE TITLE
Window10 编译出错

### ISSUE THREAD

**Issue by hongyaohongyao** [shouxieai/tensorRT_Pro#35]
[ 17%] Linking CXX shared library plugin_list.dll
LINK Pass 1: command "D:\PROGRA~1\MICROS~1\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\plugin_list.dir\objects1.rsp /out:plugin_list.dll /implib:plugin_list.lib /pdb:D:\Projects\CLionProjects\smart_classroom_cpp\build\plugin_list.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL -LIBPATH:D:\Projects\CLionProjects\smart_classroom_cpp\lean\protobuf3.11.4\lib -LIBPATH:D:\Projects\CLionProjects\smart_classroom_cpp\lean\TensorRT8.0.1.6\lib -LIBPATH:D:\Projects\CLionProjects\smart_classroom_cpp\lean\cuda11.1\lib\x64 -LIBPATH:D:\Projects\CLionProjects\smart_classroom_cpp\lean\cudnn8.2.1\lib\x64 -LIBPATH:D:\Projects\CLionProjects\smart_classroom_cpp\lean\opencv3.4.6\lib -LIBPATH:D:\Projects\CLionProjects\smart_classroom_cpp\lean\pthread\lib D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64\cudart.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\plugin_list.dir/intermediate.manifest CMakeFiles\plugin_list.dir/manifest.res" failed (exit code 1120) with the following output:
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_yolo_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_yolov5_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_yolox_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_preprocess_kernel.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_centernet_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_dbface_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_retinaface_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_scrfd_decode.cu.obj : error LNK2001: 无法解析的外部符号 "void __cdecl iLogger::__log_func(char const *,int,enum iLogger::LogLevel,char const *,...)" (?__log_func@iLogger@@YAXPEBDHW4LogLevel@1@0ZZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_yolo_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_yolov5_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_yolox_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_preprocess_kernel.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_centernet_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_dbface_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_retinaface_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_scrfd_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::grid_dims(int)" (?grid_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_yolo_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_yolov5_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_yolox_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_preprocess_kernel.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_centernet_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_dbface_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_retinaface_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_scrfd_decode.cu.obj : error LNK2001: 无法解析的外部符号 "struct dim3 __cdecl CUDATools::block_dims(int)" (?block_dims@CUDATools@@YA?AUdim3@@H@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 getPluginRegistry，该符号在函数 "public: __cdecl nvinfer1::PluginRegistrar<class DCNv2PluginCreator__>::PluginRegistrar<class DCNv2PluginCreator__>(void)" (??0?$PluginRegistrar@VDCNv2PluginCreator__@@@nvinfer1@@QEAA@XZ) 中被引用
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 getPluginRegistry
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 getPluginRegistry
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)，该符号在函数 "public: __cdecl cv::String::~String(void)" (??1String@cv@@QEAA@XZ) 中被引用
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "int __cdecl TRT::data_type_size(enum TRT::DataType)" (?data_type_size@TRT@@YAHW4DataType@1@@Z)，该符号在函数 "public: virtual unsigned __int64 __cdecl DCNv2::getWorkspaceSize(struct nvinfer1::PluginTensorDesc const *,int,struct nvinfer1::PluginTensorDesc const *,int)const " (?getWorkspaceSize@DCNv2@@UEBA_KPEBUPluginTensorDesc@nvinfer1@@H0H@Z) 中被引用
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl ONNXPlugin::GTensor::count(int)const " (?count@GTensor@ONNXPlugin@@QEBAHH@Z)，该符号在函数 "void __cdecl enqueue_native<float>(struct cublasContext *,class std::vector<struct ONNXPlugin::GTensor,class std::allocator<struct ONNXPlugin::GTensor> > const &,class std::vector<struct ONNXPlugin::GTensor,class std::allocator<struct ONNXPlugin::GTensor> > &,class std::vector<struct ONNXPlugin::GTensor,class std::allocator<struct ONNXPlugin::GTensor> > const &,void *,struct CUstream_st *)" (??$enqueue_native@M@@YAXPEAUcublasContext@@AEBV?$vector@UGTensor@ONNXPlugin@@V?$allocator@UGTensor@ONNXPlugin@@@std@@@std@@AEAV12@1PEAXPEAUCUstream_st@@@Z) 中被引用
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: int __cdecl ONNXPlugin::GTensor::count(int)const " (?count@GTensor@ONNXPlugin@@QEBAHH@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: int __cdecl ONNXPlugin::GTensor::count(int)const " (?count@GTensor@ONNXPlugin@@QEBAHH@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl ONNXPlugin::GTensor::offset_array(unsigned __int64,int const *)const " (?offset_array@GTensor@ONNXPlugin@@QEBAH_KPEBH@Z)，该符号在函数 "public: int __cdecl ONNXPlugin::GTensor::offset<>(int)const " (??$offset@$$V@GTensor@ONNXPlugin@@QEBAHH@Z) 中被引用
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::configurePlugin(struct nvinfer1::DynamicPluginTensorDesc const *,int,struct nvinfer1::DynamicPluginTensorDesc const *,int)" (?configurePlugin@TRTPlugin@ONNXPlugin@@UEAAXPEBUDynamicPluginTensorDesc@nvinfer1@@H0H@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::configurePlugin(struct nvinfer1::DynamicPluginTensorDesc const *,int,struct nvinfer1::DynamicPluginTensorDesc const *,int)" (?configurePlugin@TRTPlugin@ONNXPlugin@@UEAAXPEBUDynamicPluginTensorDesc@nvinfer1@@H0H@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::configurePlugin(struct nvinfer1::DynamicPluginTensorDesc const *,int,struct nvinfer1::DynamicPluginTensorDesc const *,int)" (?configurePlugin@TRTPlugin@ONNXPlugin@@UEAAXPEBUDynamicPluginTensorDesc@nvinfer1@@H0H@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "public: virtual __cdecl ONNXPlugin::TRTPlugin::~TRTPlugin(void)" (??1TRTPlugin@ONNXPlugin@@UEAA@XZ)，该符号在函数 "public: virtual __cdecl DCNv2::~DCNv2(void)" (??1DCNv2@@UEAA@XZ) 中被引用
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual __cdecl ONNXPlugin::TRTPlugin::~TRTPlugin(void)" (??1TRTPlugin@ONNXPlugin@@UEAA@XZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual __cdecl ONNXPlugin::TRTPlugin::~TRTPlugin(void)" (??1TRTPlugin@ONNXPlugin@@UEAA@XZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl ONNXPlugin::TRTPlugin::pluginInit(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,void const *,unsigned __int64)" (?pluginInit@TRTPlugin@ONNXPlugin@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBX_K@Z)，该符号在函数 "public: virtual class nvinfer1::IPluginV2DynamicExt * __cdecl DCNv2PluginCreator__::deserializePlugin(char const *,void const *,unsigned __int64)" (?deserializePlugin@DCNv2PluginCreator__@@UEAAPEAVIPluginV2DynamicExt@nvinfer1@@PEBDPEBX_K@Z) 中被引用
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl ONNXPlugin::TRTPlugin::pluginInit(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,void const *,unsigned __int64)" (?pluginInit@TRTPlugin@ONNXPlugin@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBX_K@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl ONNXPlugin::TRTPlugin::pluginInit(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,void const *,unsigned __int64)" (?pluginInit@TRTPlugin@ONNXPlugin@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBX_K@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 "public: virtual class std::shared_ptr<struct ONNXPlugin::LayerConfig> __cdecl ONNXPlugin::TRTPlugin::new_config(void)" (?new_config@TRTPlugin@ONNXPlugin@@UEAA?AV?$shared_ptr@ULayerConfig@ONNXPlugin@@@std@@XZ)，该符号在函数 "public: virtual class std::shared_ptr<struct ONNXPlugin::LayerConfig> __cdecl DCNv2::new_config(void)" (?new_config@DCNv2@@UEAA?AV?$shared_ptr@ULayerConfig@ONNXPlugin@@@std@@XZ) 中被引用
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual class std::shared_ptr<struct ONNXPlugin::LayerConfig> __cdecl ONNXPlugin::TRTPlugin::new_config(void)" (?new_config@TRTPlugin@ONNXPlugin@@UEAA?AV?$shared_ptr@ULayerConfig@ONNXPlugin@@@std@@XZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual class std::shared_ptr<struct ONNXPlugin::LayerConfig> __cdecl ONNXPlugin::TRTPlugin::new_config(void)" (?new_config@TRTPlugin@ONNXPlugin@@UEAA?AV?$shared_ptr@ULayerConfig@ONNXPlugin@@@std@@XZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl ONNXPlugin::TRTPlugin::supportsFormatCombination(int,struct nvinfer1::PluginTensorDesc const *,int,int)" (?supportsFormatCombination@TRTPlugin@ONNXPlugin@@UEAA_NHPEBUPluginTensorDesc@nvinfer1@@HH@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl ONNXPlugin::TRTPlugin::supportsFormatCombination(int,struct nvinfer1::PluginTensorDesc const *,int,int)" (?supportsFormatCombination@TRTPlugin@ONNXPlugin@@UEAA_NHPEBUPluginTensorDesc@nvinfer1@@HH@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl ONNXPlugin::TRTPlugin::supportsFormatCombination(int,struct nvinfer1::PluginTensorDesc const *,int,int)" (?supportsFormatCombination@TRTPlugin@ONNXPlugin@@UEAA_NHPEBUPluginTensorDesc@nvinfer1@@HH@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::getNbOutputs(void)const " (?getNbOutputs@TRTPlugin@ONNXPlugin@@UEBAHXZ)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::getNbOutputs(void)const " (?getNbOutputs@TRTPlugin@ONNXPlugin@@UEBAHXZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::getNbOutputs(void)const " (?getNbOutputs@TRTPlugin@ONNXPlugin@@UEBAHXZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::initialize(void)" (?initialize@TRTPlugin@ONNXPlugin@@UEAAHXZ)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::initialize(void)" (?initialize@TRTPlugin@ONNXPlugin@@UEAAHXZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::initialize(void)" (?initialize@TRTPlugin@ONNXPlugin@@UEAAHXZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::terminate(void)" (?terminate@TRTPlugin@ONNXPlugin@@UEAAXXZ)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::terminate(void)" (?terminate@TRTPlugin@ONNXPlugin@@UEAAXXZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::terminate(void)" (?terminate@TRTPlugin@ONNXPlugin@@UEAAXXZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl ONNXPlugin::TRTPlugin::getWorkspaceSize(struct nvinfer1::PluginTensorDesc const *,int,struct nvinfer1::PluginTensorDesc const *,int)const " (?getWorkspaceSize@TRTPlugin@ONNXPlugin@@UEBA_KPEBUPluginTensorDesc@nvinfer1@@H0H@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl ONNXPlugin::TRTPlugin::getWorkspaceSize(struct nvinfer1::PluginTensorDesc const *,int,struct nvinfer1::PluginTensorDesc const *,int)const " (?getWorkspaceSize@TRTPlugin@ONNXPlugin@@UEBA_KPEBUPluginTensorDesc@nvinfer1@@H0H@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl ONNXPlugin::TRTPlugin::getWorkspaceSize(struct nvinfer1::PluginTensorDesc const *,int,struct nvinfer1::PluginTensorDesc const *,int)const " (?getWorkspaceSize@TRTPlugin@ONNXPlugin@@UEBA_KPEBUPluginTensorDesc@nvinfer1@@H0H@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::enqueue(struct nvinfer1::PluginTensorDesc const *,struct nvinfer1::PluginTensorDesc const *,void const * const *,void * const *,void *,struct CUstream_st *)" (?enqueue@TRTPlugin@ONNXPlugin@@UEAAHPEBUPluginTensorDesc@nvinfer1@@0PEBQEBXPEBQEAXPEAXPEAUCUstream_st@@@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::enqueue(struct nvinfer1::PluginTensorDesc const *,struct nvinfer1::PluginTensorDesc const *,void const * const *,void * const *,void *,struct CUstream_st *)" (?enqueue@TRTPlugin@ONNXPlugin@@UEAAHPEBUPluginTensorDesc@nvinfer1@@0PEBQEBXPEBQEAXPEAXPEAUCUstream_st@@@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl ONNXPlugin::TRTPlugin::enqueue(struct nvinfer1::PluginTensorDesc const *,struct nvinfer1::PluginTensorDesc const *,void const * const *,void * const *,void *,struct CUstream_st *)" (?enqueue@TRTPlugin@ONNXPlugin@@UEAAHPEBUPluginTensorDesc@nvinfer1@@0PEBQEBXPEBQEAXPEAXPEAUCUstream_st@@@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl ONNXPlugin::TRTPlugin::getSerializationSize(void)const " (?getSerializationSize@TRTPlugin@ONNXPlugin@@UEBA_KXZ)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl ONNXPlugin::TRTPlugin::getSerializationSize(void)const " (?getSerializationSize@TRTPlugin@ONNXPlugin@@UEBA_KXZ)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl ONNXPlugin::TRTPlugin::getSerializationSize(void)const " (?getSerializationSize@TRTPlugin@ONNXPlugin@@UEBA_KXZ)
plugin_list_generated_DCNv2.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::serialize(void *)const " (?serialize@TRTPlugin@ONNXPlugin@@UEBAXPEAX@Z)
plugin_list_generated_HSigmoid.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::serialize(void *)const " (?serialize@TRTPlugin@ONNXPlugin@@UEBAXPEAX@Z)
plugin_list_generated_HSwish.cu.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl ONNXPlugin::TRTPlugin::serialize(void *)const " (?serialize@TRTPlugin@ONNXPlugin@@UEBAXPEAX@Z)
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 cublasGetMathMode，该符号在函数 "enum cublasStatus_t __cdecl cublasMigrateComputeType(struct cublasContext *,enum cudaDataType_t,enum cublasComputeType_t *)" (?cublasMigrateComputeType@@YA?AW4cublasStatus_t@@PEAUcublasContext@@W4cudaDataType_t@@PEAW4cublasComputeType_t@@@Z) 中被引用
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 cublasSgemm_v2，该符号在函数 "void __cdecl segemm_native(struct cublasContext *,enum cublasOperation_t,enum cublasOperation_t,int,int,int,float,float const *,int,float const *,int,float,float *,int)" (?segemm_native@@YAXPEAUcublasContext@@W4cublasOperation_t@@1HHHMPEBMH2HMPEAMH@Z) 中被引用
plugin_list_generated_DCNv2.cu.obj : error LNK2019: 无法解析的外部符号 cublasGemmEx，该符号在函数 "enum cublasStatus_t __cdecl cublasGemmEx(struct cublasContext *,enum cublasOperation_t,enum cublasOperation_t,int,int,int,void const *,void const *,enum cudaDataType_t,int,void const *,enum cudaDataType_t,int,void const *,void *,enum cudaDataType_t,int,enum cudaDataType_t,enum cublasGemmAlgo_t)" (?cublasGemmEx@@YA?AW4cublasStatus_t@@PEAUcublasContext@@W4cublasOperation_t@@1HHHPEBX2W4cudaDataType_t@@H23H2PEAX3H3W4cublasGemmAlgo_t@@@Z) 中被引用
plugin_list.dll : fatal error LNK1120: 23 个无法解析的外部命令
NMAKE : fatal error U1077: “"D:\Program Files\JetBrains\CLion 2021.2\bin\cmake\win\bin\cmake.exe"”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by shouxieai** [comment]
你用的cmake在windows下的编译，这个不建议使用，本身也没考虑windows下用cmake，你更应该用visual studio。
否则cmakefilelists.txt就得在插件上加入所有的依赖项
