### ISSUE TITLE
Environment Configuration Issues！

### ISSUE THREAD

**Issue by Havehandssook** [shouxieai/tensorRT_Pro#37]
![QQ截图20211119174416](https://user-images.githubusercontent.com/74224500/142601516-d69d224a-b9a0-43c0-8494-e65522894d8c.jpg)
![QQ截图20211119173519](https://user-images.githubusercontent.com/74224500/142600868-9bec6b28-16c5-4c68-b132-8a6825073aa2.jpg)
I have never used VS Code before. I want to learn from the video of the blogger, but there are always errors. Is there any solution？（I have installed Tensorrt on Windows）

**Comment by shouxieai** [comment]
如果是windows，请使用visual studio 2017以及以上版本，打开解决方案“TensorRT.sln”进行编译
如果是vscode，请连接linux服务器并进行配置运行。使用cmake或者makefile进行,makefile可以参考：https://zhuanlan.zhihu.com/p/396448133

**Comment by Havehandssook** [comment]
> 如果是windows，请使用visual studio 2017以及以上版本，打开解决方案“TensorRT.sln”进行编译 如果是vscode，请连接linux服务器并进行配置运行。使用cmake或者makefile进行,makefile可以参考：https://zhuanlan.zhihu.com/p/396448133

“simple_yolo.sln”这个工程是专门针对yolo系列么，我看到“TensorRT.sln”似乎是包含了所有测试，我主要是想从您这里学到如何用c++调用tensorrt的api去推理yolov5的.onnx或者是.engine文件，我这样想对么，还是有别的地方可以学习？

**Comment by shouxieai** [comment]
simple_yolo.sln是针对yolo的，你可以参考：https://github.com/shouxieai/tensorRT_Pro/blob/main/AboutCode.zh-cn.md
得到文件结构的解释

建议你配合看b站视频：https://www.bilibili.com/video/BV1Xw411f7FW/

**Comment by Havehandssook** [comment]
我只是想找到可以推理.engine模型的代码，然后我就看到了您视频中的app_lesson.cpp对于推理只需要几步即可完成，于是我复制了这个源文件作为我工程的main.cpp，并且把所需要的头文件都移植了过去，但是还是无法运行
![QQ截图20211121225819](https://user-images.githubusercontent.com/74224500/142767187-c0d0e10b-75bb-4ecf-82f4-d44b23c78372.jpg)

**Comment by shouxieai** [comment]
你需要补充c++基础知识
