### ISSUE TITLE
src/http/ilogger.cpp:376:53: error: ‘bind’ is not a member of ‘std’                  flush_thread_.reset(new thread(std::bind(&Logger::flush_job, this)));

### ISSUE THREAD

**Issue by hellojiabin** [shouxieai/tensorRT_Pro#39]
src/http/ilogger.cpp:376:53: note: ‘std::bind’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?

src/http/ilogger.cpp:38:1:
+#include <functional>

大佬在restful_server文件夹下src/http/ilogger.cpp添加一下#include <functional>

**Comment by shouxieai** [comment]
我加我加

**Comment by shouxieai** [comment]
加了
