### ISSUE TITLE
retinaface+arcface在tensorRT7.x与tensorRT8.x耗时差别很大，这是什么原因呢？

### ISSUE THREAD

**Issue by hande6688** [shouxieai/tensorRT_Pro#40]
1.retinaface，resnet50+tensorRT8.x耗时如下：
car.jpg, 2 faces, average time: 24.85 ms
gril.jpg, 1 faces, average time: 24.85 ms
group.jpg, 24 faces, average time: 24.85 ms
yq.jpg, 1 faces, average time: 24.85 ms
zand.jpg, 2 faces, average time: 24.85 ms
zgjr.jpg, 3 faces, average time: 24.85 ms

2.retinaface，resnet50+tensorRT7.x耗时如下：
car.jpg, 2 faces, average time: 34.78 ms
gril.jpg, 1 faces, average time: 34.78 ms
group.jpg, 24 faces, average time: 34.78 ms
yq.jpg, 1 faces, average time: 34.78 ms
zand.jpg, 2 faces, average time: 34.78 ms
zgjr.jpg, 3 faces, average time: 34.78 ms

3.retinaface+arcface，resnet50+tensorrt8.X耗时如下：
2ys1.jpg_2face_time:0.060646772384643555s
2ys3.jpg_9face_time:0.12475872039794922s
2ys5.jpg_3face_time:0.09700417518615723s
2ys2.jpg_1face_time:0.053908586502075195s

4.retinaface+arcface，resnet50+tensorrt7.X耗时如下：
2ys2.jpg_1face_time:0.33365297317504883s
2ys1.jpg_2face_time:0.6880166530609131s
2ys3.jpg_9face_time:2.6245572566986084s
2ys5.jpg_3face_time:0.9589879512786865s

同一个模型在tensorRT版本上差别很大，是不是arcface跟tensorRT7.x版本的问题？

**Comment by shouxieai** [comment]
这个非常需要了解你如何测试计时的

**Comment by hande6688** [comment]
resnet50+tensorRT8.x和resnet50+tensorRT7.x，是运行make retinaface -j8测试的，用python测试耗时也是这样的结果

retinaface+arcface，resnet50+tensorrt8.X和resnet50+tensorrt7.X是python运行测试的

**Comment by shouxieai** [comment]
tensorRT8确实存在优化，这一点你得清楚下
