### ISSUE TITLE
一般思路下的做法是：我在A电脑导出 onnx, 然后在A电脑编译好对应的序列化工具（依赖tensorrt,cuda和cudnn，依赖项和工具一起打包）。 然后要在B电脑使用的时候，用这个序列化工具去序列化 onnx.   960, 1060, 1080 下都是这么做没问题。  1660 就遇到这个问题。 [E] [TRT] c:\p4sw\sw\gpgpu\MachineLearning\DIT\release\5.1\engine\cuda\cudaConvolutionLayer.cpp (238) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionLayer::execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)

### ISSUE THREAD

**Issue by wjyangqun** [shouxieai/tensorRT_Pro#42]
一般思路下的做法是：我在A电脑导出 onnx, 然后在A电脑编译好对应的序列化工具（依赖tensorrt,cuda和cudnn，依赖项和工具一起打包）。 然后要在B电脑使用的时候，用这个序列化工具去序列化 onnx. 

960, 1060, 1080 下都是这么做没问题。

1660 就遇到这个问题。
[E] [TRT] c:\p4sw\sw\gpgpu\MachineLearning\DIT\release\5.1\engine\cuda\cudaConvolutionLayer.cpp (238) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionLayer::execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)

**Comment by shouxieai** [comment]
你需要确认，cudnn是否能够适配1660这个设备上的驱动。这种问题一般都是驱动匹配问题

**Comment by wjyangqun** [comment]
> 你需要确认，cudnn 是否能够适配1660这个设备上的驱动。这种问题一般都是驱动匹配问题。

好的，谢谢
