### ISSUE TITLE
Error with int8process parameter for C++ Interface Compile for INT8 

### ISSUE THREAD

**Issue by adventurousbanana** [shouxieai/tensorRT_Pro#43]
It seems that I can't pass the recall function for INT8 without error. This is directly from the [readme](https://github.com/shouxieai/tensorRT_Pro/blob/main/README.md#the-intro-to-interface). Any help? Thank you.

![image](https://user-images.githubusercontent.com/90185427/146108089-1a75276f-da61-4e8c-a5fe-f78f989e51d0.png)

**Comment by shouxieai** [comment]
You can modify  `vector<string>& images` into `const vector<string>& images`

**Comment by adventurousbanana** [comment]
Ok I understand why this provides solution. Thanks.
