### ISSUE TITLE
yolox 的部署，拆分了所需要的代码封装成dll, 但是在dll 中，从 nvinfer runtime deserializeCudaEngine（tensorrt 提供的api） 反序列化引擎文件时，总是返回空指针。一样的代码在exe 中没问题，能反序列化，分析结果也正确。

### ISSUE THREAD

**Issue by wjyangqun** [shouxieai/tensorRT_Pro#46]
关于yolox 的部署，拆分了所需要的代码封装成dll, 但是在dll 中，从 nvinfer runtime deserializeCudaEngine（tensorrt 提供的api） 反序列化引擎文件时，总是返回空指针。一样的代码在exe 中没问题，能反序列化，分析结果也正确。
大佬知道咋回事嘛？？
![@53DUT~1TH7M}YY3AGX4PQ5](https://user-images.githubusercontent.com/62162800/146762744-09a2be06-6ee0-4589-9a15-7fbe724f7b0e.jpg)

**Comment by shouxieai** [comment]
终端有提示什么异常吗？
