### ISSUE TITLE
/usr/bin/ld: cannot find -lcuda  error

### ISSUE THREAD

**Issue by sainttelant** [shouxieai/tensorRT_Pro#48]
when i make yolo -j8 in my ubuntu system, it occurred the error as above, i have set my protobuf version to libprotoc 3.15.8 ,and compile the project with tensorrt 8.2 version, before that, i ran the use_tensorrt_8.x.sh as well, however, this error happened , i 've tried to install the libcuda via typing apt-get install libcuda-dev, but it didn' t work, cannot find the library root.   

after the investigation, i found there is no libcuda installed for high version of tensorrt 8.2, i only found the libcudart.so instead, so it is so weird. any suggestions about this error!

**Comment by shouxieai** [comment]
libcuda is installed in your system directory with the graphics card driver
