### ISSUE TITLE
是否能在JetsonNX/Xaiver设备中使用DLA

### ISSUE THREAD

**Issue by dongxuanlb** [shouxieai/tensorRT_Pro#50]
我手上有Xavier设备，不知道是否能够将脸部识别这类小模型甚至是yoloxs等跑在DLA上，这样可以同时让GPU跑其他更大的任务。

**Comment by shouxieai** [comment]
你可以设置一下DLA即可

**Comment by DCC-lzhy** [comment]
请问，你在这块板子上编译完protobuf了吗，我也是这板子

**Comment by JF-Lee** [comment]
> 请问，你在这块板子上编译完protobuf了吗，我也是这板子

请问你编译好了吗？我这边make一直opencv报错
