### ISSUE TITLE
protobuf编译有问题

### ISSUE THREAD

**Issue by DCC-lzhy** [shouxieai/tensorRT_Pro#52]
make报错
```
g++: error: google/protobuf/util/internal/.libs/proto_writer.o: No such file or directory
Makefile:2372: recipe for target 'libprotobuf.la' failed
make[2]: *** [libprotobuf.la] Error 1
```
是不是要先下载googletest，如果是的话，是不是哪个版本呢？
ubuntu18.04 jetson xavier nx

**Comment by shouxieai** [comment]
这个你需要去找找相关资料。暂时没有办法回答你。
我们测试的protobuf版本编译都没有这个问题

**Comment by DCC-lzhy** [comment]
害，我下载3.11.4，按照src/readme安装，从./autogen.sh开始，./configure会遇到一个问题
`=== configuring in third_party/googletest (/home/nvidia//protobuf-3.11.4/third_party/googletest)
configure: WARNING: no configuration information is in third_party/googletest`
按照网上的操作，把googletest下载放进去也不行。
最后我从头开始
`    git clone https://github.com/protocolbuffers/protobuf.git
    cd protobuf
    git submodule update --init --recursive`
就可以了。
PS：直接用release版可以吗，但release里没lib文件夹，我看在cmakelists三里有指定链接的库目录

**Comment by DCC-lzhy** [comment]
```
FAIL: protobuf-test
PASS: protobuf-lazy-descriptor-test
PASS: protobuf-lite-test
PASS: google/protobuf/compiler/zip_output_unittest.sh
PASS: google/protobuf/io/gzip_stream_unittest.sh
PASS: protobuf-lite-arena-test
PASS: no-warning-test
============================================================================
Testsuite summary for Protocol Buffers 3.19.3
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```
make是通过了，但make check失败了，网上说是内存不够，这块板子就8.0G，怎么办

**Comment by DCC-lzhy** [comment]
我编译通过了，git clone -b v3.11.4，可以了
