### ISSUE TITLE
cmake编译失败

### ISSUE THREAD

**Issue by sungh66** [shouxieai/tensorRT_Pro#56]
cmake能全部正常build，但是在make的时候正常编译到85%的时候报错了，以下是报错内容（我未修改报错文件内的代码）

> [ 83%] Building CXX object CMakeFiles/pro.dir/src/application/app_yolo_fast.cpp.o
> [ 83%] Building CXX object CMakeFiles/pro.dir/src/application/app_alphapose.cpp.o
> [ 85%] Building CXX object CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o
> In file included from /xxx/datav/projects/tensorRT_Pro/src/application/app_python/interface.cpp:6:0:
> /xxx/datav/projects/tensorRT_Pro/src/application/tools/pybind11.hpp:159:20: fatal error: Python.h: No such file or directory
>  #include <Python.h>
>                     ^
> compilation terminated.
> CMakeFiles/pro.dir/build.make:1142: recipe for target 'CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o' failed
> make[3]: *** [CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:328: recipe for target 'CMakeFiles/pro.dir/all' failed
> make[2]: *** [CMakeFiles/pro.dir/all] Error 2
> CMakeFiles/Makefile2:537: recipe for target 'CMakeFiles/yolo.dir/rule' failed
> make[1]: *** [CMakeFiles/yolo.dir/rule] Error 2
> Makefile:300: recipe for target 'yolo' failed
> make: *** [yolo] Error 2

**Comment by sungh66** [comment]
@shouxieai cmake的方法的错误上面的还未解决，make也有错误，在link时出现错误，貌似是opencv缺少依赖，但是我拉的是你提供的云盘中解压的环境

> Link workspace/pro
> /usr/bin/ld: warning: libdc1394.so.22, needed by /home/highsai/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libavcodec.so.58, needed by /home/highsai/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libavformat.so.58, needed by /home/highsai/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libavutil.so.56, needed by /home/highsai/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libswscale.so.5, needed by /home/highsai/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `avformat_find_stream_info@LIBAVFORMAT_58'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `avcodec_find_decoder@LIBAVCODEC_58'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `dc1394_feature_whitebalance_get_value'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `sws_scale@LIBSWSCALE_5'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `avformat_close_input@LIBAVFORMAT_58'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `dc1394_camera_enumerate'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `av_dict_set@LIBAVUTIL_56'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `dc1394_feature_set_mode'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `av_read_frame@LIBAVFORMAT_58'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_core.so: undefined reference to `logf@GLIBC_2.27'
> /home/xx/Download/C++/datav/lean/opencv-4.2.0/lib/libopencv_videoio.so: undefined reference to `av_mallocz@LIBAVUTIL_56'
> collect2: error: ld returned 1 exit status
> Makefile:87: recipe for target 'workspace/pro' failed
> make: *** [workspace/pro] Error 1

**Comment by shouxieai** [comment]
你最好自己编译本地的opencv

**Comment by sungh66** [comment]
感谢回复，已解决！

**Comment by buaaxiejun** [comment]
> cmake可以全部正常构建，在make的时候正常编译到85%的时候报错了，下面是报错内容（我未修改报错文件内的代码）
> 
> > [ 83%] 构建 CXX 对象 CMakeFiles/pro.dir/src/application/app_yolo_fast.cpp.o 
> > [ 83%] 构建 CXX 对象 CMakeFiles/pro.dir/src/application/app_alphapose.cpp.o 
> > [ 85%] 构建 CXX对象 CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o
> > 在 /xxx/datav/projects/tensorRT_Pro/src/application/app_python/interface.cpp:6:0: 
> > /xxx/datav/中包含的文件中projects/tensorRT_Pro/src/application/tools/pybind11.hpp:159:20：致命错误：Python.h：没有这样的文件或目录
> > #include <Python.h> 
> > ^
> > 编译终止。
> > CMakeFiles/pro.dir/build.make:1142：目标“CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o”的配方失败
> > make[3]: *** [CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o] 错误 1 
> > ​​make[3]: *** Waiting for unfinished jobs.... 
> > CMakeFiles/Makefile2:328 : 目标'CMakeFiles/pro.dir/all'的配方失败
> > make[2]: *** [CMakeFiles/pro.dir/all] 错误 2 
> > CMakeFiles/Makefile2:537: 目标'CMakeFiles/yolo.dir/rule 的配方' 失败
> > make[1]: *** [CMakeFiles/yolo.dir/rule] 错误 2 
> > Makefile:300: 目标 'yolo' 的配方失败
> > make: *** [yolo] 错误 2

请教一下，第一个问题是怎么解决的呀？

**Comment by ZhixiongSun** [comment]
> > cmake可以全部正常构建，在make的时候正常编译到85%的时候报错了，下面是报错内容（我未修改报错文件内的代码）
> > > [ 83%] 构建 CXX 对象 CMakeFiles/pro.dir/src/application/app_yolo_fast.cpp.o
> > > [ 83%] 构建 CXX 对象 CMakeFiles/pro.dir/src/application/app_alphapose.cpp.o
> > > [ 85%] 构建 CXX对象 CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o
> > > 在 /xxx/datav/projects/tensorRT_Pro/src/application/app_python/interface.cpp:6:0:
> > > /xxx/datav/中包含的文件中projects/tensorRT_Pro/src/application/tools/pybind11.hpp:159:20：致命错误：Python.h：没有这样的文件或目录
> > > #include <Python.h>
> > > ^
> > > 编译终止。
> > > CMakeFiles/pro.dir/build.make:1142：目标“CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o”的配方失败
> > > make[3]: *** [CMakeFiles/pro.dir/src/application/app_python/interface.cpp.o] 错误 1
> > > ​​make[3]: *** Waiting for unfinished jobs....
> > > CMakeFiles/Makefile2:328 : 目标'CMakeFiles/pro.dir/all'的配方失败
> > > make[2]: *** [CMakeFiles/pro.dir/all] 错误 2
> > > CMakeFiles/Makefile2:537: 目标'CMakeFiles/yolo.dir/rule 的配方' 失败
> > > make[1]: *** [CMakeFiles/yolo.dir/rule] 错误 2
> > > Makefile:300: 目标 'yolo' 的配方失败
> > > make: *** [yolo] 错误 2
> 
> 请教一下，第一个问题是怎么解决的呀？

Hi, you should modify this line in CMakeLists set(PythonRoot "/home/sun/miniconda3/envs/trt") to your own python envs root
