### ISSUE TITLE
frame rate of mp4 file doesn't correspond to inference time 

### ISSUE THREAD

**Issue by hygxy** [shouxieai/tensorRT_Pro#59]
After running the ```./pro arface_tracker``` command, I obtain a result.mp4. The result is correct and when I right-click the result.mp4 video->properties->Details, I see a frame rate of **30** frames/second.

But when I test the inference time in the file ```app_arcface.cpp``` as follows:
```cpp
unordered_map<int,MotionFiler> MotionFiler;
while(cap.read(image)){
auto begin_time = iLogger::timestamp_now_float();
auto faces = detector->commit(image).get();
//other inference code including deepsort part and drawing rectangles
float inference_time = (iLogger::timestamp_now_float() - begin_timer);
INFO("inference_time: %.2f ms",inference_time);
writer.write(image);
}
```
I see the inference time is between **80** ms and **160** ms, which doesn't correspond to the frame rate(**30** fps) found in the properties of the result.mp4 video. Why is that so and btw. how can I measure the inference time correctly in code? thanks in advance!

**Comment by shouxieai** [comment]
Inference performance can only get the maximum benefit under multi batch. It is not obvious when use a single picture.

**Comment by hygxy** [comment]
直接讲中文吧，不管国际友人了。就是这个arcface_tracker这个项目的检测部分和deepsort里提取特征的部分真的很厉害，就算单张图放进去推理，耗时也能接受。但是deepsort自身的耗时很大，在我的硬件上(NVIDIA AGX Xavier)和推理部分相比要差一个数量级。关于提升deepsort自身的性能，您有啥好的建议吗？

另外还想问请教一个与这个issue不太相关的问题，就是视频里有提到针对成百上千路的视频，可以采用把计算过程抽象成一张图的方式，我想问下为何这样就能提升性能，只是缩短(重叠)等待的时间吗？

期待回复，谢谢！

**Comment by shouxieai** [comment]
deepsort的性能问题，需要对里面的逻辑代码进行优化，里面有很多集合操作，以及相似度计算操作。这部分工作我暂时没考虑做。因为很多场景跟踪也还ok
针对很多路视频，优化重叠时间能带来大量收益。你大可以在纸上画画时序图就会发现，很多中间过程都浪费在等待上了。另外这么做也充分利用了GPU的计算密集型效率最好的特性
