### ISSUE TITLE
Jetson Nano 编译retinaface失败

### ISSUE THREAD

**Issue by LUOQING1994** [shouxieai/tensorRT_Pro#60]
环境：Jetson Nano 4G ，jetPack 4.6、cuda 10.2、Tensorrt 8、Opencv 4.5.5、protobuf 3.19.3
描述：安装Retinaface支持，在执行sudo make retinaface -j6时 报如下错误
![image](https://user-images.githubusercontent.com/20340633/151286742-ee6c66eb-1ed9-42a6-beb6-f974b1b5bf90.png)
备注：tensorrt、cuda等都是使用的系统自带

**Comment by shouxieai** [comment]
你这个错误很奇怪，是bash错误，你系统哪里配置了bash吗？

**Comment by LUOQING1994** [comment]
问题已解决，已成功编译

**Comment by Glory-Peng** [comment]
兄弟你好，我最近也在搞Retinaface，可以加个联系方式交流下吗
