### ISSUE TITLE
关于yolov5的v6版本的使用问题

### ISSUE THREAD

**Issue by WangRongsheng** [shouxieai/tensorRT_Pro#61]
1. 请问，使用yolov5的v6版本使用tensorrt部署，根据github文档来还是根据你视频中来？
2. github仓库中的yolov5的v6版本根据你提供的方法修改yolo.py文件，导出会报错，请问是否可以测试更新下？

**Comment by shouxieai** [comment]
http://zifuture.com:1556/fs/pypi/code_template/yolov5-6.0-py-cpp.zip
你下载这个，里面有我改好的，可以直接使用
