### ISSUE TITLE
make yolo -j3时出错，求解答

### ISSUE THREAD

**Issue by Pong-97** [shouxieai/tensorRT_Pro#75]
![14700712911a2621ac8674930677b91](https://user-images.githubusercontent.com/73111023/158936185-a43f49b4-b39b-4a02-9664-66888fb33f98.png)
在跟着视频拉取tensorrt-pro的模板的时候，遇到这个问题。
请问这是我自己电脑配置的问题吗？
如果可以自动配置路径和版本的话，按理说不会出现这种错误吧？
求解答，谢谢！

**Comment by shouxieai** [comment]
你的cuda没有找到，你需要查看系统是否有libcuda.so。若没有请执行软连接：ln -s /xxx/libcuda.so.1 /xxx/libcuda.so




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shouxieai/tensorRT_Pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 中午12:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[shouxieai/tensorRT_Pro] make yolo -j3时出错，求解答 (Issue #75)





 

 在跟着视频拉取tensorrt-pro的模板的时候，遇到这个问题。
 请问这是我自己电脑配置的问题吗？
 如果可以自动配置路径和版本的话，按理说不会出现这种错误吧？
 求解答，谢谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pong-97** [comment]
感谢大佬，用您提供的方法已解决问题
