### ISSUE TITLE
tensorRT_Pro/simple_yolo/src/simple_yolo.cu   sync=false 推理时是否同步设置为false是否会异常？

### ISSUE THREAD

**Issue by QZ1219** [shouxieai/tensorRT_Pro#79]
老师，您好，请问这个是否是 代码小bug？

simple_yolo.cu  文件的地1887行，推理时同步设置为false，是否会出现未推理结束，就进行后处理(nms)，结果异常

正常的是不是应该设置为sync =true ？

https://github.com/shouxieai/tensorRT_Pro/blob/f92ccb31f62a5917d04adfa05bfa0629c8b7aec8/simple_yolo/src/simple_yolo.cu#L1887
engine->forward(false);  其它app也是一样的

**Comment by QZ1219** [comment]
https://github.com/shouxieai/tensorRT_Pro/blob/f92ccb31f62a5917d04adfa05bfa0629c8b7aec8/simple_yolo/src/simple_yolo.cu#L1887
engine->forward(false);  其它app也是一样的

**Comment by shouxieai** [comment]
这个true或者false只是控制是否多一行，cudaStreamSynchronize(stream)
只要你通过output->cpu拿结果，这里面的to_cpu也会为你加上cudaStreamSynchronize(stream)。
所以大部分时候你会发现给true或者false没有啥区别

**Comment by QZ1219** [comment]
谢谢，明白了，forward之后的decode_kernel_invoker过程也是在GPU运行，所以不需要cudaStreamSynchronize(stream)，
只有后续output_array_device.to_cpu();这个执行的时候会加上cudaStreamSynchronize(stream)，
