### ISSUE TITLE
preprocess  engine->forward  decode_kernel_invoker  线程问题

### ISSUE THREAD

**Issue by QZ1219** [shouxieai/tensorRT_Pro#80]
老师，您好，preprocess  在commits，是在主线程执行，而decode_kernel_invoker是在work 函数中和forward在一个线程中执行，为什么会这么设计呀？
如果送入的图片存在高并发问题是否会导致主线程卡死在commits中，为什么不把preprocess过程和decode一样放在work线程中执行？

然后我有个想法是不是可以把preprocess  和decode 剥离出来，通过多线程实现，  work只做forward的工作，这样是不是更高效？

**Comment by shouxieai** [comment]
且不说commits，你看commit函数哈，我们假设commit函数会高并发，有n个线程调用commit提交内容：
你注意看preprocess，应该把他分为两个部分：
1. 数据准备：cpu内存复制、gpu内存复制、affine矩阵计算等，小的操作
2. 核函数：warpaffine函数的调用

步骤1的在commit执行的这个线程上。然后步骤2的核函数warpaffine使用的是stream_，也就是跟推理用的是同一个流。
其执行时序图里面，关于cpu必要的预处理，比如内存copy仿射矩阵计算等等轻量级，分散在commit提交这个线程中，也就是n个线程在这部分工作是并行的。然后把准备好的东西提交到worker中，worker中对所有数据处理依旧是并行的。因此其并行处理的地方更好。

若把preprocess的放到worker中，在worker内也没办法对这些常规的预处理进行并行，使用串行性能更差

**Comment by QZ1219** [comment]
谢谢老师，那decode是串行的为什么没有从preprocess剥离，是因为耗时小对性能影响可以忽略？

**Comment by shouxieai** [comment]
decode他是全cuda代码，放到GPU加速收益比较大

**Comment by shouxieai** [comment]
他在cuda上就是并行的
