### ISSUE TITLE
memcpy(image_host, image.data, size_image);  image.data为什么不直接拷贝到gpu

### ISSUE THREAD

**Issue by QZ1219** [shouxieai/tensorRT_Pro#81]
https://github.com/shouxieai/tensorRT_Pro/blob/f92ccb31f62a5917d04adfa05bfa0629c8b7aec8/simple_yolo/src/simple_yolo.cu#L1962

老师，您好，请问此处为什么把数据先从malloc申请的cpu内存拷贝到cudaMallocHost申请的cpu内存，然后再拷贝到GPU内存，
而不是直接从image.data拷贝到GPU内存了？

**Comment by shouxieai** [comment]
我们列举一下流程，malloc分配的是pageable memory，mallocHost分配的是pinned memory
对于pageable memory -> GPU流程如下：
1. malloc pinned memory
2. pageable memory -> pinned memory
3. pinned memory -> GPU
4. free pinned memory

对于pinned memory -> GPU 流程如下：
1. pinned memory -> GPU

那么我们手动先复制到host，再到GPU，实际上就是避免频繁alloc pinned memory，free pinned memory，让他减少内存分配次数。最后的实际效果也确实是有明显的提速

**Comment by QZ1219** [comment]
谢谢老师
