### ISSUE TITLE
nms的cuda加速实现

### ISSUE THREAD

**Issue by xuyufeng1995** [shouxieai/tensorRT_Pro#85]
nms_kernel中遍历所有目标框，for循环中假设第一个目标框得分为0.9，第二个得分为0.8，两个框iou大于阈值，对于第二个线程不会标记0.8为ignore，因为得分0.9的目标框的数组位置在得分0.8的目标框前面。

**Comment by shouxieai** [comment]
0.9那个线程他会把0.8个标记为 ignore的

**Comment by xuyufeng1995** [comment]
![image](https://user-images.githubusercontent.com/45379784/164158341-41496c8e-6364-43bd-8edb-c790a9de2c9b.png)
假设只有一个分类，图中红框内是计算当前目标框与其他目标框的IOU值，如果出现一个目标框得分比当前大且IOU大于阈值就将当前标记为Ignore。存在三个目标框A(0.9),B(0.8),C(0.7)，括号内为得分，A和B的IOU，B和C的IOU都大于阈值，在线程A内没有任何操作，而在线程B内发现A和B的IOU大于阈值，会将B标记为ignore，并退出，在线程C内发现B和C的IOU大于阈值，会将C标记为ignore，这样C也会被删掉，这样的结果是不对的。

**Comment by shouxieai** [comment]
这个确实不对，这一点也注明了，像你说的这种属于corner case，实际使用很难遇到或者几乎遇不到这种情况。
这也是没有做sort的引入的一个问题。
所以如果你工作中推理可以用这个fast nms。如果测量mAP，可以使用CPU的nms
而且也实际测试过CUDA nms与CPU标准nms的mAP指标，相差不超过0.01

之所以这么做的好处是代码简单，好实现，相比其他的实现而言更简单了

**Comment by shouxieai** [comment]
请参照这里的备注：
https://github.com/shouxieai/tensorRT_Pro/blob/d577fbab615a3d84cb50824d2418655659fd61af/src/application/app_yolo/yolo.hpp#L29

**Comment by shouxieai** [comment]
这里的corner cases指的是你所说的

**Comment by xuyufeng1995** [comment]
好的，我测试了一下，确实精度损失较小，非常感谢
