### ISSUE TITLE
请教下如何转出fp16 且 dynamic batch size 的yolov5 tensorRT?

### ISSUE THREAD

**Issue by MrRace** [shouxieai/tensorRT_Pro#87]
YOLOV5官方的 export.py 对于导出ONNX格式的时候似乎不支持同时设置`--dynamic`和`--half`，那么如果想要得到 batch size 是dynamic的，且 float 16的yolov5 tensorRT，该如何操作？在哪里设置fp16的相关参数？谢谢~

**Comment by shouxieai** [comment]
导出无所谓fp16，在tensorRT编译时指定fp16就可以了

**Comment by MrRace** [comment]
> 导出无所谓fp16，在tensorRT编译时指定fp16就可以了

@shouxieai  tensorRT编译的时候怎么指定 fp16？ trtexec 命令有 `--fp16` 这个参数，在这个仓库中具体改动哪个文件？求下指导，谢谢！
