### ISSUE TITLE
python接口报错

### ISSUE THREAD

**Issue by GitHub-LYY** [shouxieai/tensorRT_Pro#93]
bboxes = yolo.commit(image).get()

在执行这条语句的时候，报错，
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    bboxes = yolo.commit(image).get()
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by shouxieai** [comment]
你需要通过代码编译后得到python接口代码，方能执行这些
否则，通过pip install的话，不能够这么操作，需要import trtpy.init_default as trtpy
