### ISSUE TITLE
您好，请问一下人脸识别部分是不是没有用到face_alignment啊？我没有找到显示使用的位置，我自己加了对齐后发现效果不佳。如果使用了可以麻烦你告知一下吗？谢谢啦

### ISSUE THREAD

**Issue by liudan8** [shouxieai/tensorRT_Pro#95]

**Comment by shouxieai** [comment]
使用了对齐，请参照：https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/src/application/app_arcface/arcface.cpp#L27  计算得到矩阵
这里做的对齐：https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/src/application/app_arcface/arcface.cpp#L227

**Comment by liudan8** [comment]
嗯嗯，感谢您的回复，这个我看到了，但是没找到在哪里调用了这个函数，所以想问你在哪调用了这个？

**Comment by liudan8** [comment]
Mat crop;
        tie(crop, face) = RetinaFace::crop_face_and_landmark(image, face);
        Arcface::landmarks landmarks;
        memcpy(landmarks.points, face.landmark, sizeof(landmarks.points));
       


        // // 人脸对齐
        // crop = Arcface::face_alignment(crop,landmarks);

        string crop_file = iLogger::format("face/crop_file_2/%s.jpg", file_name.c_str());
        imwrite(crop_file, crop);

        auto feature     = arcface->commit(make_tuple(crop, landmarks)).get();
        string face_name = file_name;
        features.push_back(feature);
        names.push_back(face_name);

        INFO("New face [%s], %d feature, %.5f", face_name.c_str(), feature.cols, face.confidence);



我在crop人脸后加入人脸对齐crop = Arcface::face_alignment(crop,landmarks); 发现效果不如不加这句的，所以我觉得您应该是哪里用到了对齐，但是我找了挺久没找到

**Comment by liudan8** [comment]
> 使用了对齐，请参照：
> 
> https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/src/application/app_arcface/arcface.cpp#L27
> 
> 计算得到矩阵
> 这里做的对齐：
> https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/src/application/app_arcface/arcface.cpp#L227

    Mat crop;
    tie(crop, face) = RetinaFace::crop_face_and_landmark(image, face);
    Arcface::landmarks landmarks;
    memcpy(landmarks.points, face.landmark, sizeof(landmarks.points));
   


    // // 人脸对齐
    // crop = Arcface::face_alignment(crop,landmarks);

    string crop_file = iLogger::format("face/crop_file_2/%s.jpg", file_name.c_str());
    imwrite(crop_file, crop);

    auto feature     = arcface->commit(make_tuple(crop, landmarks)).get();
    string face_name = file_name;
    features.push_back(feature);
    names.push_back(face_name);

    INFO("New face [%s], %d feature, %.5f", face_name.c_str(), feature.cols, face.confidence);
我在crop人脸后加入人脸对齐crop = Arcface::face_alignment(crop,landmarks); 发现效果不如不加这句的，所以我觉得您应该是哪里用到了对齐，但是我找了挺久没找到，想问问在哪？

**Comment by shouxieai** [comment]
回复的地方就是调用的地方啊

**Comment by shouxieai** [comment]
他是在这里：https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/src/application/app_arcface/arcface.cpp#L171   计算的矩阵
然后在这里，送入并执行warpAffine的：
https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/src/application/app_arcface/arcface.cpp#L195

**Comment by liudan8** [comment]
了解了，谢谢您！
