### ISSUE TITLE
tensorRT_Pro/python/trtpy/__init__.py

### ISSUE THREAD

**Issue by QZ1219** [shouxieai/tensorRT_Pro#99]
老师您好，请问tensorRT_Pro/python/trtpy/__init__.py 这个python文件是用来干什么的呀？看的不是很明白，C++接口导出为python接口，这是什么用法？有参考资料吗，谢谢！

**Comment by shouxieai** [comment]
这个是python的模块接口实现的规则，当你import trtpy的时候，会执行__init__.py。__init__.py更像是一个document，让你能够看到有哪些函数和参数，然后通过https://github.com/shouxieai/tensorRT_Pro/blob/f24e4921e23e71d16771ab7d4df601f71da7dac2/python/trtpy/__init__.py#L319
这句话覆盖函数类的定义，变为c++中的定义。
具体参考pybind11

**Comment by QZ1219** [comment]
知道了，非常谢谢！
